import {
  ArrowRight,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  X,
  Workflow,
  Calendar,
  MapPin,
  ThumbsUp
} from 'lucide-react';
import React from 'react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  calendar: Calendar,
  mapPin: MapPin,
  star: () => (
    React.createElement('svg', {
      xmlns: 'http://www.w3.org/2000/svg',
      width: '24',
      height: '24',
      viewBox: '0 0 24 24',
      fill: 'currentColor', // Solid fill for the star
      stroke: 'none', // No outline
      className: 'lucide lucide-star',
    },
    React.createElement('path', {d: 'm12 2 3.09 6.26 6.91.5-5 5.05 1.18 6.88L12 16.47l-6.18 3.25 1.18-6.88-5-5.05 6.91-.5L12 2z'})
    )
  ),
  thumbsup: ThumbsUp,
};

export {Icons};
